### PR TITLE
[front] fix: include isManager on MCP metadata snapshot mock auth

### PR DESCRIPTION
**Pull request by frankaloia**
## Summary
- Fixes main CI (`MCP Servers Metadata Snapshot > should not have any servers with extraction errors`) broken by #30732.
- `workspace_people` gates tool registration on `auth.isManager()`, but the snapshot mock only implemented `isAdmin`. Extraction threw `auth.isManager is not a function`.

## Test plan
- tests pass

## Deploy
1. deploy front

### CODE REVIEW

**Comment by smb2268** [comment]
Lgtm
